name: bot18 # you probably want to 'snapcraft register <name>'
version: '0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Bot18 is a high-frequency cryptocurrency trading bot. # 79 char long summary
description: |
  More info on Bot18: https://bot18.net/

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  bot18:
    # See 'snapcraft plugins'
    plugin: nil
