name: bot18
version: git
summary: A high-frequency cryptocurrency trading bot.
description: |
  More info available at: https://bot18.net/

grade: stable
confinement: strict

apps:
  bot18:
    command: ./bot18.sh
    daemon: simple

parts:
  bot18:
    plugin: nodejs
    source: .

icon: gui/public/assets/bot18_icon.png
