name: bot18
version: git
summary: A high-frequency cryptocurrency trading bot by Zenbot creator @carlos8f
description: |
  More info available at: https://bot18.net/

grade: stable
confinement: strict

apps:
  bot18:
    command: npx bot18
    daemon: simple

parts:
  bot18:
    plugin: nodejs
    source: .

icon: gui/public/assets/bot18_icon.png
